[package]
name = "mahan/minefield"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
bufferize = "egomoose/bufferize@2.1.0"
countryservice = "prooheckcp/countryservice@0.2.4"
cmdr = "evaera/cmdr@1.12.0"
promise = "evaera/promise@4.0.0"
trove = "sleitnick/trove@1.8.0"
satchel = "ronarudoog/satchel@0.1.0"
ezvisualz = "arxkdev/ezvisualz@0.0.6"

[server-dependencies]
profilestore = "vyon/profilestore@1.0.3"
